### ISSUE TITLE
Cannot import android.app.ActivityThread;

### ISSUE THREAD

**Issue by airhandsome** [kevinross/android_debuggable_tool#4]
I down load this git project but can't used in the new android studio. 
Therefore I create the gradle-wrapper.properties as the following code;
`#Tue Nov 09 17:12:44 CST 2021
distributionBase=GRADLE_USER_HOME
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
distributionPath=wrapper/dists
zipStorePath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
`
After syncing. The package android.app.ActivityThread cannot be imported.
Is there anything I do wrong?

**Comment by kevinross** [comment]
Hi @airhandsome 

I haven't even _looked_ at this project since around the time of the most recent commit, which is several years ago.

As for why that package couldn't be imported: first, it's not a package, it's a fully qualified class name (the class' name is "ActivityThread" and it's in package "android.app"). Second... well, it's been about the same amount of time since I last poked around android. I'm afraid I can't help :(
